### PR TITLE
Ens lookup

### PR DESCRIPTION
**Pull request by jester7**
Fixed useENSName hook and added ENSLookup component.

### CODE REVIEW

**Comment by jester7** [comment]
FYI the only way to test this right now is by appending a query string to the Vercel preview URL like ?wallet=something, because currently wallet addresses aren't displayed much. After a second or two the wallet address will change to the ENS if there is one.

**Comment by slinlee** [comment]
Hi @jester7 The functionality looked fine on the deployed demo. nice, 👍🏽 

I haven't had a chance to look closely at the code yet though. @epan might have comments for improvements, but he'll be away from the computer the next few days.

**Comment by slinlee** [comment]
btw, it would be an extra bonus if you could add a cypress automated test for this functionality.

Let me know if you need more info about that.  @jester7

**Comment by jester7** [comment]
> btw, it would be an extra bonus if you could add a cypress automated test for this functionality.
> 
> Let me know if you need more info about that. @jester7

Hey @slinlee , sure thing. I've never done cypress tests before, but it looks straightforward enough. Just to double check, I should put my tests inside a new .js file in cypress/integration/ , correct? If you could just confirm I've got the right idea, I'll read the docs for cypress and model mine after the others that are already in that directory.

**Comment by slinlee** [comment]
@jester7 yeah, in this case a new file makes sense, since I named the other ones a bit specifically. 
I think just two tests, one that loads the:
- url with `?wallet=` with ens
- url with `?wallet=` without ens

and basically any other tests that you were running manually to make sure the feature worked.

**Comment by jester7** [comment]
@slinlee All tests passed on my local machine. I was looking for a more generic ens name and address to test against but it seems all reverse lookups of smart contract addresses associated with the ENS organization fail, such as ens.eth and resolver.eth. All personal addresses I threw at it worked, though. I also looked into using intercept() in cypress but given that lookups issue over a dozen requests, it seemed too complicated and good enough to leave these as simple tests.

**Comment by jester7** [comment]
btw we should probably add a className like address or wallet-address to the <p> element or anywhere wallet addresses are used but for now the cy.get("nav > a > p") selector works.

**Pull request merged**
