### PR TITLE
Run E2E tests on each PR

### LINKED ISSUE #181: Enable E2E tests for all PR
Right now they only are run after merging to `main` which is when they are also being deployed to prod. This means each PR needs more manual testing.

The test suite is run in parallel so it doesn't add any more time.

### PR DESCRIPTION
**Pull request by slinlee**
- Removes redundant test run when PR are created.
- Resolves #181 - Runs the E2E tests for each PR

### CODE REVIEW

**Review by slavingia — APPROVED** [review]

**Comment by archae0pteryx** [comment]
@slinlee I actually disabled this because the e2e tests make actual api requests and I thought it wasn't the most optimal thing so i made it check only on PR's to master. I put in an issue to add the fixtures for cypress (i actually already have example responses for everything in `lib/polygon/__mocks__`

**Comment by archae0pteryx** [comment]
You're gonna have to set the condition on the if in the job block if you do wanna run it for everything.

**Comment by slinlee** [comment]
> @slinlee I actually disabled this because the e2e tests make actual api requests and I thought it wasn't the most optimal thing so i made it check only on PR's to master. I put in an issue to add the fixtures for cypress (i actually already have example responses for everything in `lib/polygon/__mocks__` so we could turn on the e2e for everything.

@archae0pteryx - Yep! I remember reading that. I agree that making actual API calls during tests isn't ideal. At the time I went with it because they're read only and it was faster for getting tests in place. If we don't run E2E tests automatically, we lose some of the benefit of having that coverage, you know what I mean?

**Comment by archae0pteryx** [comment]
> > @slinlee I actually disabled this because the e2e tests make actual api requests and I thought it wasn't the most optimal thing so i made it check only on PR's to master. I put in an issue to add the fixtures for cypress (i actually already have example responses for everything in `lib/polygon/__mocks__` so we could turn on the e2e for everything.
> 
> @archae0pteryx - Yep! I remember reading that. I agree that making actual API calls during tests isn't ideal. At the time I went with it because they're read only and it was faster for getting tests in place. If we don't run E2E tests automatically, we lose some of the benefit of having that coverage, you know what I mean?

For sure. That makes total sense. I'll work on getting those fixtures setup soon. Like i mentioned i already have all the responses we need for it. just need to plug them in.

**Pull request merged**
