### PR TITLE
Refactor /api/polygon endpoint

### PR DESCRIPTION
**Pull request by archae0pteryx**
Purpose:
Previously this was all crammed into a single file and was near impossible to test and reuse. This refactor separates all polygon related api calls upstream and all game checks. This pattern leans heavily on CLEAN architecture principles and is completely typed and 90+% covered.

- Separated game logic and the api calls underneath.
- Refactored some of the structure to make a little more sense. I'm open to any other patterns.
- Filled in all the tests for the original logic and all the added logic. I'm not sold on the `__test__` folder pattern. It's what i'm used to so i went with it.
- Reworked the debugging endpoint situation so it's not avail in production env

### NOTE: Contains `refactor/account-component` branch. 
I needed to build off of that before the PR went in. This was to reduce merge conflicts. GH wouldn't let me do a PR into a PR when forks are involved unfortunately.

A lot of the files changes were just import updates and types movement as well as a lot of tests. The meat and potatoes live in the `lib/polygon` folder - especially the `validators` file. This is where all of the game logic lives. I separated out the groups of tasks based on which api call needed to be made to get the info. You can see those groups in `lib/polygon/api`.

### CODE REVIEW

**Comment by slinlee** [comment]
Just some general comments from me:

@archae0pteryx you can set the target for the PR to be `refactor/account-component` and github will automatically change it for you when that PR is merged. (or at least... it usually works :) )

As for the debug url param, that was pretty handy for testing, esp for vercel test deployments for PRs. What do you think about setting a param `DEBUG_ENABLED=true` but for prod that is set to false?

**Comment by archae0pteryx** [comment]
@slinlee It wouldn't let me do the PR to another PR here because it's across forks unfortunately. As far as the DEBUG_ENABLED situation, if i'm understanding you correctly, you want to have an override to allow it for "production" (vercel deploys) should you need it?

**Comment by slinlee** [comment]
> @slinlee It wouldn't let me do the PR to another PR here because it's across forks unfortunately. 

Ah yeah, I didn't notice that. You're right :)

> As far as the DEBUG_ENABLED situation, if i'm understanding you correctly, you want to have an override to allow it for "production" (vercel deploys) should you need it?

Almost. So production should not have debugging allowed. But it would be useful if debugging is turned on by default on vercel preview deployments and local dev.


> 
> edit: You made me realize i had alread put in a check for a debug flag regardless of env. I adjusted it a little so now when `DEBUG_ENABLE` is truthy, it will not only log out all the requests and responses at the debug console level but also let you send the debug dots var as well. The README is updated to reflect this.

The URL based debugging can be added back, but it should use  the new flag you introduced to lock it down for production.

**Comment by archae0pteryx** [comment]
> > @slinlee It wouldn't let me do the PR to another PR here because it's across forks unfortunately.
> 
> Ah yeah, I didn't notice that. You're right :)
> 
> > As far as the DEBUG_ENABLED situation, if i'm understanding you correctly, you want to have an override to allow it for "production" (vercel deploys) should you need it?
> 
> Almost. So production should not have debugging allowed. But it would be useful if debugging is turned on by default on vercel preview deployments and local dev.
> 
> > edit: You made me realize i had alread put in a check for a debug flag regardless of env. I adjusted it a little so now when `DEBUG_ENABLE` is truthy, it will not only log out all the requests and responses at the debug console level but also let you send the debug dots var as well. The README is updated to reflect this.
> 
> The URL based debugging can be added back, but it should use the new flag you introduced to lock it down for production.

If i remember correctly, vercel sets the node env to production for preview deploys as well? I think that's the case but we can set env/branch specific vars for prod deploys.

**Comment by slinlee** [comment]
@archae0pteryx This PR might need some re-jiggering to show the right diff.

**Comment by archae0pteryx** [comment]
@slinlee and @slavingia Gonna merge this. I've tested it quite a bit.

**Pull request merged**
