### PR TITLE
Add prettier and eslint as pre-commit hooks

### PR DESCRIPTION
**Pull request by slinlee**
@epan this enables the pre-commit for eslint and prettier.

image

This is the approach where is analyzes and cleans the whole staged file rather than just the staged blocks. So it should only be committed when we run prettier on everything :)

### CODE REVIEW

**Comment by epan** [comment]
Related to https://github.com/slavingia/fweb3.xyz/pull/83

**Comment by slavingia** [comment]
merge conflicts

**Comment by epan** [comment]
I can resolve conflicts quickly

**Comment by slinlee** [comment]
> I can resolve conflicts quickly

thanks. yeah yarn.lock ones are easy.

**Comment by epan** [comment]
in this case, i did the following to resolve
1. delete `yarn.lock` bc the README says to use `npm install`, not `yarn` and i dont think projects are really supposed to have both `package-lock.json` AND a `yarn.lock`
2. `rm -rf node_modules` to reset 
3. run `npm install` to make sure things would reflect a state of new contributor and that everything still works

Screen Shot 2022-02-25 at 9 45 37 AM

**Pull request closed without merging**
